#!/usr/bin/env python
# -*- coding: utf-8 -*-
# пример программки сервера на python

import socket

sock = socket.socket()
sock.bind(('', 9090)) # set host, port
sock.listen(1) # кол-во соединений
conn, addr = sock.accept() # 

print 'connected:', addr

while True:
    data = conn.recv(1024)
    if not data:
        break
    conn.send(data.upper())

conn.close()